#!/usr/bin/env bash

set -e

STARTING_DIR=$PWD
cd $HOME
echo '================================================================================'
echo 'Preparing dotfile install ...'
sudo -v # ensure we only type password once

type php &>/dev/null && current_php_version=$(php -r "echo PHP_VERSION;" | cut -d. -f-2) 

# echo '================================================================================'

if test ! $(which brew); then
    echo '================================================================================'
    echo 'Installing homebrew...'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    echo 'Done installing homebrew.'
    echo '================================================================================'
fi

# if test ! -e $HOME/.vim/autoload/plug.vim; then
#     echo '================================================================================'
#     echo 'Installing vim-plug...'
#     curl --create-dirs -fLo $HOME/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     echo 'Done installing vim-plug.'
#     echo '================================================================================'
# fi

# # @see: https://intelephense.com/faq.html
# if test ! -e $HOME/intelephense/licence.txt; then
#     echo '================================================================================'
#     echo 'Setting up Intelephense license...'
#     mkdir -p $HOME/intelephense
#     echo 'Enter your Intelephense license key:'
#     read -s INTELEPHENSE_LICENSE_KEY
#     echo $INTELEPHENSE_LICENSE_KEY > $HOME/intelephense/licence.txt
#     echo 'Done setting up Intelephense license.'
#     echo '================================================================================'
# fi

echo '================================================================================'
echo 'Linking dotfiles...'
/bin/bash $HOME/dotfiles/link
echo 'Done linking dotfiles.'
# echo '================================================================================'



echo '================================================================================'
echo 'Installing, updating, and cleaning up brew dependencies...'

#sudo chown -R $(id -un) /usr/local/Cellar/{php*,dnsmasq*,nginx*} &>/dev/null || true

export HOMEBREW_NO_INSTALL_CLEANUP=true 

brew bundle --global
#brew bundle cleanup --force --global
# brew services cleanup
# sudo brew services cleanup
#brew cleanup
echo 'Done installing, updating, and cleaning up brew dependencies.'
# echo '================================================================================'

# echo '================================================================================'
# echo 'Installing and updating composer dependencies...'
# composer global update --with-all-dependencies
# echo 'Done installing and updating composer dependencies.'
# echo '================================================================================'


# /bin/bash $HOME/dotfiles/link


# echo '================================================================================'
# echo 'Installing and updating npm dependencies...'
# npm install -g npm@latest
# npm update -g
# echo 'Done installing and updating npm dependencies.'
# echo '================================================================================'

# echo '================================================================================'
# echo 'Installing and updating pecl dependencies...'
# pecl update-channels
# # For whatever reason, brew is symlinking to the following directory, but it doesn't exist
# # and extensions can't be installed. This should resolve that.
# mkdir /usr/local/lib/php/pecl -p
# # pecl upgrade will also install if it isn't yet installed, where as pecl
# # install will fail if it is installed.
# pecl upgrade pcov
# echo 'Done installing and updating pecl dependencies.'
# echo '================================================================================'

# echo '================================================================================'
# echo 'Installing and updating FZF...'
# /usr/local/opt/fzf/install --key-bindings --completion --update-rc --no-bash --no-fish
# echo 'Done installing and updating FZF.'
# echo '================================================================================'

echo '================================================================================'
echo 'Installing and updating terminal themes...'
for theme in 3024_Day AtomOneLight PencilLight Material Spring ayu_light; do 
    THEME=https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/${theme}.conf
    wget -q "$THEME" -P ~/.config/kitty/themes
done
echo 'Done installing and updating terminal themes.'
# echo '================================================================================'

# Additionally, if you receive “zsh compinit: insecure directories” warnings
# when attempting to load these completions, you may need to run this
# see: https://docs.brew.sh/Shell-Completion
# compaudit | xargs chmod g-w

echo '================================================================================'
echo 'Setting defaults.'
if test -r $HOME/.defaults; then
    source .defaults || true
fi
# echo '================================================================================'

# As we rely on valet, switch_php and php_install for handling the differences in php installation
# we need to inform those scripts that dotfiles and brew bundle has recently run.
date > $HOME/.dotfile_lastrun

# https://scriptingosx.com/2017/04/about-bash_profile-and-bashrc-on-macos/
# Alternative to dotfiles - https://yadm.io


source $HOME/dotfiles/files/switch_php
switch_php "${current_php_version:-8.1}"
echo "Done"
exit 0

# for now for a php restart as we are often in old 7.0

echo -e "Check and Fix Php (yN) ? " && read valetphp
case $valetphp in
    [Yy]* )        
        [ -r $HOME/dotfiles/files/switch_php ] && {
            source $HOME/dotfiles/files/switch_php
            switch_php "${current_php_version:-8.1}"
            #sudo chown -R $(id -un) /usr/local/Cellar/{php*,dnsmasq*,nginx*} &>/dev/null || true
            # if this fails run php_uninstall and then switch_php 8.1
        }
        ;;
esac

echo 'Done!'
